#pragma once

#include <string>

#include "../../DataStructures/RAPTOR/Data.h"
#include "../../DataStructures/TimeTable/Data.h"
#include "../../Shell/Shell.h"

using namespace Shell;

class RAPTORToTimeTable : public ParameterizedCommand {
public:
  RAPTORToTimeTable(BasicShell &shell)
      : ParameterizedCommand(
            shell, "raptorToTimeTable",
            "Converts a RAPTOR object into a TimeTable object.") {
    addParameter("Input binary (RAPTOR Data)");
    addParameter("Output binary (TimeTable data)");
  }

  virtual void execute() noexcept {
    const std::string inputFile = getParameter("Input binary (RAPTOR Data)");
    const std::string outputFile =
        getParameter("Output binary (TimeTable data)");

    RAPTOR::Data data(inputFile);
    data.printInfo();

    TimeTable::Data timeTable(data);
    timeTable.printInfo();
    timeTable.serialize(outputFile);
  }
};

class LoadAndApplyPartition : public ParameterizedCommand {
public:
  LoadAndApplyPartition(BasicShell &shell)
      : ParameterizedCommand(
            shell, "loadAndApplyPartition",
            "Loads a partition file generated by a black-box partitioner and "
            "applies the cell ids to the stops.") {
    addParameter("Input partition file");
    addParameter("Input binary (TimeTable Data)");
  }

  virtual void execute() noexcept {
    const std::string partitionFile = getParameter("Input partition file");
    const std::string timetableFile =
        getParameter("Input binary (TimeTable Data)");

    TimeTable::Data timeTable(timetableFile);
    timeTable.printInfo();

    timeTable.createCompactLayoutGraph();
    timeTable.readPartitionFile(partitionFile);

    timeTable.serialize(timetableFile);
  }
};
